import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cryptoarth/shared/theme/app_colors.dart';

import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cryptoarth/features/strategies/providers/strategy_provider.dart';

class CodeGeneratorScreen extends ConsumerStatefulWidget {
  const CodeGeneratorScreen({super.key});

  @override
  ConsumerState<CodeGeneratorScreen> createState() => _CodeGeneratorScreenState();
}

class _CodeGeneratorScreenState extends ConsumerState<CodeGeneratorScreen> {
  String? _selectedStrategy;
  String _selectedLanguage = 'MQL4';
  final TextEditingController _codeController = TextEditingController();

  final List<String> _languages = ['AFL', 'Python', 'Pine', 'MQL4'];

  @override
  void initState() {
    super.initState();
    _updateCode();
  }

  void _updateCode() {
    // Mock code generation based on selection
    String code = '';
    
    if (_selectedLanguage == 'MQL4') {
      code = '''
// $_selectedStrategy Strategy for MQL4
// Generated by Crypto Arth AI

#property copyright "Crypto Arth AI"
#property link      "https://cryptoarth.ai"
#property version   "1.00"
#property strict

input double TakeProfit = 50.0;
input double StopLoss = 30.0;
input double LotSize = 0.1;

// Global variables
int ticket;

// Init function
int OnInit() {
   Print("Strategy Started: $_selectedStrategy");
   return(INIT_SUCCEEDED);
}

// Tick function
void OnTick() {
   // Trading logic goes here...
   // Check for $_selectedStrategy conditions
   
   if(ticket <= 0) {
      // Open order logic
   }
}
''';
    } else if (_selectedLanguage == 'Python') {
       code = '''
# $_selectedStrategy Strategy for Python
# Generated by Crypto Arth AI

import pandas as pd
import numpy as np

class Strategy:
    def __init__(self, data):
        self.data = data
        
    def generate_signals(self):
        print("Analyzing with $_selectedStrategy...")
        
        # Calculate indicators
        # Generate buy/sell signals
        
        return signals

if __name__ == "__main__":
    # Load data
    data = pd.read_csv('market_data.csv')
    strategy = Strategy(data)
    strategy.generate_signals()
''';
    } else if (_selectedLanguage == 'Pine') {
       code = '''
// $_selectedStrategy Strategy for Pine Script
// Generated by Crypto Arth AI
//@version=5
strategy("$_selectedStrategy", overlay=true)

// Input parameters
fastLength = input(12, "Fast Length")
slowLength = input(26, "Slow Length")
signalLength = input(9, "Signal Length")

// Calculations
[macdLine, signalLine, hist] = ta.macd(close, fastLength, slowLength, signalLength)

// Strategy Logic
if (ta.crossover(macdLine, signalLine))
    strategy.entry("Long", strategy.long)

if (ta.crossunder(macdLine, signalLine))
    strategy.close("Long")
''';
    } else {
      code = '// $_selectedStrategy code for $_selectedLanguage\n// Functionality coming soon...';
    }

    setState(() {
      _codeController.text = code;
    });
  }

  @override
  void dispose() {
    _codeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Code Generator',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
            ),
            Text(
              'Export AI strategies',
              style: TextStyle(fontSize: 10, color: Colors.white.withOpacity(0.6)),
            ),
          ],
        ),
        backgroundColor: AppColors.background,
        iconTheme: const IconThemeData(color: Colors.white),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(12.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Compact Strategy Selection
            ref.watch(strategyProvider).when(
              data: (strategies) {
                final List<String> strategyNames = strategies.map((s) => s.strategyName).toList();
                if (strategyNames.isEmpty) {
                  return const Text("No strategies available", style: TextStyle(color: Colors.white54));
                }
                
                // Initialize selected strategy if null
                if (_selectedStrategy == null || !strategyNames.contains(_selectedStrategy)) {
                  WidgetsBinding.instance.addPostFrameCallback((_) {
                    if (mounted) {
                      setState(() {
                         _selectedStrategy = strategyNames.first;
                         _updateCode();
                      });
                    }
                  });
                }
                
                return Row(
                  children: [
                    const Text("Strategy:", style: TextStyle(color: Colors.white70, fontSize: 12)),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Container(
                        height: 36,
                        padding: const EdgeInsets.symmetric(horizontal: 12),
                        decoration: BoxDecoration(
                          color: AppColors.cardSurface,
                          borderRadius: BorderRadius.circular(8),
                          border: Border.all(color: Colors.white.withOpacity(0.1)),
                        ),
                        child: DropdownButtonHideUnderline(
                          child: DropdownButton<String>(
                            value: _selectedStrategy ?? strategyNames.first,
                            dropdownColor: AppColors.cardSurface,
                            icon: const Icon(Icons.keyboard_arrow_down, size: 16, color: AppColors.textSecondary),
                            isExpanded: true,
                            style: const TextStyle(color: Colors.white, fontSize: 12),
                            onChanged: (String? newValue) {
                              if (newValue != null) {
                                setState(() {
                                  _selectedStrategy = newValue;
                                  _updateCode();
                                });
                              }
                            },
                            items: strategyNames.map<DropdownMenuItem<String>>((String value) {
                              return DropdownMenuItem<String>(
                                value: value,
                                child: Text(value, maxLines: 1, overflow: TextOverflow.ellipsis),
                              );
                            }).toList(),
                          ),
                        ),
                      ),
                    ),
                  ],
                );
              },
              loading: () => const Center(child: CircularProgressIndicator(color: AppColors.cyan)),
              error: (e, s) => Center(child: Text("Error: $e", style: const TextStyle(color: Colors.red))),
            ),

            const SizedBox(height: 12),

            // Compact Language Selection
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: _languages.map((lang) {
                final isSelected = _selectedLanguage == lang;
                return ChoiceChip(
                  label: Text(lang, style: TextStyle(
                    fontSize: 10, 
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                    color: isSelected ? Colors.black : Colors.white70
                  )),
                  selected: isSelected,
                  selectedColor: AppColors.gold,
                  backgroundColor: AppColors.cardSurface,
                  padding: const EdgeInsets.symmetric(horizontal: 4, vertical: 0),
                  visualDensity: VisualDensity.compact,
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(6), 
                    side: BorderSide(color: isSelected ? AppColors.gold : Colors.white.withOpacity(0.1))
                  ),
                  onSelected: (bool selected) {
                    if (selected) {
                      setState(() {
                        _selectedLanguage = lang;
                        _updateCode();
                      });
                    }
                  },
                );
              }).toList(),
            ),

            const SizedBox(height: 16),

            // Code View Header
            Row(
               mainAxisAlignment: MainAxisAlignment.spaceBetween,
               children: [
                  Row(
                    children: [
                      const Icon(Icons.code, color: AppColors.purple, size: 16),
                      const SizedBox(width: 4),
                      Text(
                        "Generated Code",
                        style: TextStyle(color: Colors.white.withOpacity(0.9), fontSize: 12, fontWeight: FontWeight.bold),
                      ),
                    ],
                  ),
                  Container(
                     padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                     decoration: BoxDecoration(
                        color: AppColors.purple.withOpacity(0.1),
                        borderRadius: BorderRadius.circular(4),
                        border: Border.all(color: AppColors.purple.withOpacity(0.3)),
                     ),
                     child: Text(
                        _selectedLanguage,
                        style: const TextStyle(color: AppColors.purple, fontWeight: FontWeight.bold, fontSize: 10),
                     ),
                  )
               ],
            ),
            
            const SizedBox(height: 8),
            
            // Code Editor
            Container(
              height: 250,
              decoration: BoxDecoration(
                color: const Color(0xFF0F1115),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.white.withOpacity(0.1)),
              ),
              child: Column(
                children: [
                   // Mac-style window controls
                   Container(
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                      decoration: BoxDecoration(
                        border: Border(bottom: BorderSide(color: Colors.white.withOpacity(0.05))),
                      ),
                      child: Row(
                         children: [
                            _buildWindowDot(const Color(0xFFFF5F57)),
                            const SizedBox(width: 6),
                            _buildWindowDot(const Color(0xFFFFBD2E)),
                            const SizedBox(width: 6),
                            _buildWindowDot(const Color(0xFF28C840)),
                            const SizedBox(width: 12),
                            Expanded(child: Text(
                               '${(_selectedStrategy ?? "strategy").toLowerCase().replaceAll(' ', '_')}.${_selectedLanguage.toLowerCase()}',
                               style: TextStyle(color: Colors.white.withOpacity(0.3), fontSize: 10),
                               overflow: TextOverflow.ellipsis,
                            )),
                         ],
                      ),
                   ),
                   Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(12.0),
                        child: TextField(
                          controller: _codeController,
                          style: const TextStyle(
                            color: Colors.greenAccent, 
                            fontFamily: 'Courier',
                            fontSize: 11,
                            height: 1.3,
                          ),
                          maxLines: null,
                          readOnly: true,
                          decoration: const InputDecoration(
                            border: InputBorder.none,
                            isDense: true,
                          ),
                        ),
                      ),
                   ),
                ],
              ),
            ),

            const SizedBox(height: 16),

            // Action Buttons
            Row(
               children: [
                  Expanded(
                    child: SizedBox(
                      height: 32,
                      child: ElevatedButton.icon(
                         onPressed: () {
                            Clipboard.setData(ClipboardData(text: _codeController.text));
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(content: Text('Code copied!')),
                            );
                         },
                         icon: const Icon(Icons.copy, size: 14),
                         label: const Text('Copy Code', style: TextStyle(fontSize: 11)),
                         style: ElevatedButton.styleFrom(
                            backgroundColor: AppColors.purple,
                            foregroundColor: Colors.white,
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                            padding: EdgeInsets.zero,
                         ),
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: SizedBox(
                      height: 32,
                      child: OutlinedButton.icon(
                         onPressed: () {
                            ScaffoldMessenger.of(context).showSnackBar(
                              const SnackBar(content: Text('Downloading...')),
                            );
                         },
                         icon: const Icon(Icons.download, size: 14),
                         label: const Text('Download', style: TextStyle(fontSize: 11)),
                         style: OutlinedButton.styleFrom(
                            foregroundColor: AppColors.cyan,
                            side: const BorderSide(color: AppColors.cyan),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                            padding: EdgeInsets.zero,
                         ),
                      ),
                    ),
                  ),
               ],
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildWindowDot(Color color) {
    return Container(
      width: 10,
      height: 10,
      decoration: BoxDecoration(
        color: color,
        shape: BoxShape.circle,
      ),
    );
  }
}
