import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:cryptoarth/shared/theme/app_colors.dart';

class CodeGeneratorScreen extends StatefulWidget {
  const CodeGeneratorScreen({super.key});

  @override
  State<CodeGeneratorScreen> createState() => _CodeGeneratorScreenState();
}

class _CodeGeneratorScreenState extends State<CodeGeneratorScreen> {
  String _selectedStrategy = 'MACD Crossover'; // Default value
  String _selectedLanguage = 'MQL4';
  final TextEditingController _codeController = TextEditingController();

  final List<String> _strategies = [
    'MACD Crossover',
    'RSI Oversold/Overbought',
    'Bollinger Bands Squeeze',
    'Moving Average Cross',
    'SuperTrend Strategy'
  ];

  final List<String> _languages = ['AFL', 'Python', 'Pine', 'MQL4'];

  @override
  void initState() {
    super.initState();
    _updateCode();
  }

  void _updateCode() {
    // Mock code generation based on selection
    String code = '';
    
    if (_selectedLanguage == 'MQL4') {
      code = '''
// $_selectedStrategy Strategy for MQL4
// Generated by Crypto Arth AI

#property copyright "Crypto Arth AI"
#property link      "https://cryptoarth.ai"
#property version   "1.00"
#property strict

input double TakeProfit = 50.0;
input double StopLoss = 30.0;
input double LotSize = 0.1;

// Global variables
int ticket;

// Init function
int OnInit() {
   Print("Strategy Started: $_selectedStrategy");
   return(INIT_SUCCEEDED);
}

// Tick function
void OnTick() {
   // Trading logic goes here...
   // Check for $_selectedStrategy conditions
   
   if(ticket <= 0) {
      // Open order logic
   }
}
''';
    } else if (_selectedLanguage == 'Python') {
       code = '''
# $_selectedStrategy Strategy for Python
# Generated by Crypto Arth AI

import pandas as pd
import numpy as np

class Strategy:
    def __init__(self, data):
        self.data = data
        
    def generate_signals(self):
        print("Analyzing with $_selectedStrategy...")
        
        # Calculate indicators
        # Generate buy/sell signals
        
        return signals

if __name__ == "__main__":
    # Load data
    data = pd.read_csv('market_data.csv')
    strategy = Strategy(data)
    strategy.generate_signals()
''';
    } else if (_selectedLanguage == 'Pine') {
       code = '''
// $_selectedStrategy Strategy for Pine Script
// Generated by Crypto Arth AI
//@version=5
strategy("$_selectedStrategy", overlay=true)

// Input parameters
fastLength = input(12, "Fast Length")
slowLength = input(26, "Slow Length")
signalLength = input(9, "Signal Length")

// Calculations
[macdLine, signalLine, hist] = ta.macd(close, fastLength, slowLength, signalLength)

// Strategy Logic
if (ta.crossover(macdLine, signalLine))
    strategy.entry("Long", strategy.long)

if (ta.crossunder(macdLine, signalLine))
    strategy.close("Long")
''';
    } else {
      code = '// $_selectedStrategy code for $_selectedLanguage\n// Functionality coming soon...';
    }

    setState(() {
      _codeController.text = code;
    });
  }

  @override
  void dispose() {
    _codeController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Code Generator',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
            ),
            Text(
              'Export your Pine Script using Claude-powered conversions',
              style: TextStyle(fontSize: 10, color: Colors.white.withOpacity(0.6)),
            ),
          ],
        ),
        backgroundColor: AppColors.background,
        iconTheme: const IconThemeData(color: Colors.white),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.of(context).pop(),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Strategy Selection
            const Text(
              "Strategy",
              style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: AppColors.cardSurface,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.white.withOpacity(0.1)),
              ),
              child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                  value: _selectedStrategy,
                  dropdownColor: AppColors.cardSurface,
                  icon: const Icon(Icons.keyboard_arrow_down, color: AppColors.textSecondary),
                  isExpanded: true,
                  style: const TextStyle(color: Colors.white, fontSize: 14),
                  onChanged: (String? newValue) {
                    if (newValue != null) {
                      setState(() {
                        _selectedStrategy = newValue;
                        _updateCode();
                      });
                    }
                  },
                  items: _strategies.map<DropdownMenuItem<String>>((String value) {
                    return DropdownMenuItem<String>(
                      value: value,
                      child: Text(value),
                    );
                  }).toList(),
                ),
              ),
            ),

            const SizedBox(height: 24),

            // Language Selection
            SingleChildScrollView(
              scrollDirection: Axis.horizontal,
              child: Row(
                children: _languages.map((lang) {
                  final isSelected = _selectedLanguage == lang;
                  return Padding(
                    padding: const EdgeInsets.only(right: 12.0),
                    child: InkWell(
                      onTap: () {
                        setState(() {
                          _selectedLanguage = lang;
                          _updateCode();
                        });
                      },
                      borderRadius: BorderRadius.circular(8),
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                        decoration: BoxDecoration(
                          color: isSelected 
                             ? AppColors.primary.withOpacity(0.2) 
                             : AppColors.cardSurface,
                          border: Border.all(
                            color: isSelected ? AppColors.gold : Colors.white.withOpacity(0.1),
                          ),
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Row(
                          children: [
                            if (lang == 'AFL' || lang == 'Pine') // Add code icons just for visual variety
                              const Padding(
                                 padding: EdgeInsets.only(right: 6),
                                 child: Icon(Icons.code, size: 16, color: Colors.white70),
                              ),
                            Text(
                              lang,
                              style: TextStyle(
                                color: isSelected ? AppColors.gold : Colors.white70,
                                fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                              ),
                            ),
                            if (isSelected)
                              Container(
                                 margin: const EdgeInsets.only(left: 6),
                                 padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                                 decoration: BoxDecoration(
                                   color: AppColors.gold,
                                   borderRadius: BorderRadius.circular(4),
                                 ),
                                 child: const Text('Premium', 
                                    style: TextStyle(color: Colors.black, fontSize: 10, fontWeight: FontWeight.bold)
                                 ),
                              ),
                          ],
                        ),
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),

            const SizedBox(height: 32),

            // Generated Code Section
            Row(
               mainAxisAlignment: MainAxisAlignment.spaceBetween,
               children: [
                  RichText(
                    text: const TextSpan(
                      children: [
                        WidgetSpan(
                          child: Padding(
                            padding: EdgeInsets.only(right: 8.0),
                            child: Icon(Icons.code, color: AppColors.purple, size: 20),
                          ),
                        ),
                        TextSpan(
                          text: "Generated Code",
                          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16),
                        ),
                      ],
                    ),
                  ),
                  Container(
                     padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
                     decoration: BoxDecoration(
                        color: AppColors.purple.withOpacity(0.2),
                        borderRadius: BorderRadius.circular(8),
                        border: Border.all(color: AppColors.purple),
                     ),
                     child: Text(
                        _selectedLanguage,
                        style: const TextStyle(color: AppColors.purple, fontWeight: FontWeight.bold, fontSize: 12),
                     ),
                  )
               ],
            ),
            
            const SizedBox(height: 12),
            
            Container(
              height: 300,
              decoration: BoxDecoration(
                color: const Color(0xFF0F1115), // Darker code background
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.white.withOpacity(0.1)),
              ),
              child: Column(
                children: [
                   // Mac-style window controls
                   Container(
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                      decoration: BoxDecoration(
                        border: Border(bottom: BorderSide(color: Colors.white.withOpacity(0.05))),
                      ),
                      child: Row(
                         children: [
                            _buildWindowDot(const Color(0xFFFF5F57)),
                            const SizedBox(width: 8),
                            _buildWindowDot(const Color(0xFFFFBD2E)),
                            const SizedBox(width: 8),
                            _buildWindowDot(const Color(0xFF28C840)),
                            const SizedBox(width: 16),
                            Text(
                               '${_selectedStrategy.toLowerCase().replaceAll(' ', '_')}.${_selectedLanguage.toLowerCase()}',
                               style: TextStyle(color: Colors.white.withOpacity(0.3), fontSize: 12),
                            ),
                         ],
                      ),
                   ),
                   Expanded(
                      child: Padding(
                        padding: const EdgeInsets.all(16.0),
                        child: TextField(
                          controller: _codeController,
                          style: const TextStyle(
                            color: Colors.greenAccent, 
                            fontFamily: 'Courier',
                            fontSize: 14,
                            height: 1.4,
                          ),
                          maxLines: null,
                          readOnly: true,
                          decoration: const InputDecoration(
                            border: InputBorder.none,
                          ),
                        ),
                      ),
                   ),
                   
                   // Action Buttons Bar
                   Padding(
                      padding: const EdgeInsets.all(16.0),
                      child: Row(
                         children: [
                            ElevatedButton.icon(
                               onPressed: () {
                                  Clipboard.setData(ClipboardData(text: _codeController.text));
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    const SnackBar(content: Text('Code copied to clipboard!')),
                                  );
                               },
                               icon: const Icon(Icons.copy, size: 18),
                               label: const Text('Copy'),
                               style: ElevatedButton.styleFrom(
                                  backgroundColor: AppColors.purple,
                                  foregroundColor: Colors.white,
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                               ),
                            ),
                            const SizedBox(width: 12),
                            OutlinedButton.icon(
                               onPressed: () {
                                  ScaffoldMessenger.of(context).showSnackBar(
                                    const SnackBar(content: Text('Downloading file...')),
                                  );
                               },
                               icon: const Icon(Icons.download, size: 18),
                               label: const Text('Download'),
                               style: OutlinedButton.styleFrom(
                                  foregroundColor: AppColors.cyan,
                                  side: const BorderSide(color: AppColors.cyan),
                                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                               ),
                            ),
                         ],
                      ),
                   ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildWindowDot(Color color) {
    return Container(
      width: 10,
      height: 10,
      decoration: BoxDecoration(
        color: color,
        shape: BoxShape.circle,
      ),
    );
  }
}
